config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :username, presence: true, length: {minimum: 5}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, 
              uniqueness: {case_sensitive: true}
    has_secure_password
    validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
    def home 
    end

    def help
    end
    
    def about 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav id="navbar-example2" class="navbar">
  <%= link_to image_tag("instagram.png", border: 1, width: 40, height: 40), '#', class: "navbar-brand" %>
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to "Followers", '#', class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Followed", '#', class: "nav-link" %>
    </li>
     <li class="nav-item">
      <%= link_to "Help", help_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "About", about_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Log in", '#', class: "nav-link" %>
    </li>
  </ul>
 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<%= render 'layouts/header' %>

app/views/static_pages/help.html.erb
<%= render 'layouts/header' %>

app/views/static_pages/home.html.erb
<%= render 'layouts/header' %>
<div class = 'info'>
<h1>Welcome to Instagram</h1> 
<p>This is my test Rails application </p>
<button type="button" class="btn btn-success"><%= link_to "Sign Up!", new_user_path, class: "nav-link"%></button>
</div>

app/views/users/new.html.erb
 <%= form_for(@user) do |f| %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name%>
        <%= f.label :first_name %>
        <%= f.text_field :first_name%>
        <%= f.label :first_name %>
        <%= f.text_field :first_name%>
        <%= f.label :first_name %>
        <%= f.text_field :first_name%>
        <%= f.submit 'Sign Up', class: "btn btn-outline-success" %>
  <%end%>